[workspace]
authors = ["Sierra Arn"]
channels = ["conda-forge"]
name = "minio-core"
platforms = ["linux-64"]
version = "0.2.1"

[tasks]

[dependencies]
python = "*"
pydantic-settings = "*"
boto3 = "*"
aioboto3 = "*"
just = "*"

[feature.test.dependencies]
jupyterlab = "*"
requests = "*"

[environments]
test = ["test"]